services:
 dynamodb-local:
   command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ."
   image: "amazon/dynamodb-local"
   container_name: dynamodb-local
   ports:
     - "8001:8000"
   working_dir: /home/dynamodblocal
   environment:
     AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
     AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'
